version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    init: true
    working_dir: "/src"
    volumes:
      - ./src:/nuxt-app
    ports:
      - "4000:4000"